apiVersion: v1
kind: Secret
metadata:
  name: xcall-backend-secrets
  namespace: learn
type: Opaque
stringData:
  REDIS_URI: "redis://:jxUZ8ckufeFn79D6z3@210.211.108.238:50062"
  API_KEY: "929f037c-7993-4072-ae43-7f9159bd9326"
  JWT_SECRET_KEY: "2O2bkHOEMVm37hHNvqe7"
  API_SECRET: "r71luuoTOnGBn8yhYOWO"
  MONGO_URI: "mongodb://smartdialog:smartdialog-dev-mongo-2024@43.239.223.37:27017/xcall?authSource=admin"
  IAM_CLIENT_SECRET: "719f037c-7993-4072-ae43-7f9159bd9326"
  AES_SECRET_KEY: "sk-proj-1234567890"